#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include "ti_msp_dl_config.h"

#define TRACK_BLACK_IS_HIGH 0U
#define TRACK_X1_IS_LEFT 1U

#define APP_MODE_SAFE_IDLE 0U
#define APP_MODE_ENCODER_DIAGNOSTIC 1U
#define APP_MODE_SPEED_TUNE 2U
#define APP_MODE_LINE_GYRO 3U
#define APP_MODE_SQUARE_3LOOP 4U
#define APP_MODE_CHASSIS_CALIBRATION 5U
#define APP_MODE_H2026 6U
#define APP_RUN_MODE APP_MODE_H2026
#define APP_ENABLE_LCD 1U
#define COMPETITION_USE_INDEPENDENT_TASKS 1U

/* Optional X42S closed-loop stepper driver; disabled to preserve car pins. */
#define APP_ENABLE_ZDT_X42S 0U

/* Enable only after a complete, verified chassis calibration run. */
#define USE_STORED_CHASSIS_CALIBRATION 0U

#define MOTOR_CHANNEL_TEST 0U
#define POWER_SWITCH_TEST 0U
#define POWER_SWITCH_TEST_DUTY_PERCENT 100U
#define POWER_SWITCH_ACTIVE_HIGH 1U
#define POWER_SWITCH_PWM_PERIOD_MS 10U
#define POWER_SWITCH_MAX_DUTY_PERCENT 100U
#define POWER_SWITCH_MAX_ON_MS 30000U

#if ((POWER_SWITCH_TEST + MOTOR_CHANNEL_TEST) > 1U)
#error "Enable only one hardware test mode at a time"
#endif

#if (APP_RUN_MODE > APP_MODE_H2026)
#error "APP_RUN_MODE is invalid"
#endif

#if (POWER_SWITCH_TEST_DUTY_PERCENT > 100U)
#error "POWER_SWITCH_TEST_DUTY_PERCENT must not exceed 100"
#endif
#define PWM_PERIOD_TICKS 200U
#define MOTOR_PWM_TIMER_PERIOD 1600U
#define MOTOR_TEST_DUTY 160U

#define CONTROL_TICK_MS 1U
#define SPEED_CONTROL_PERIOD_MS 10U
#define LINE_CONTROL_PERIOD_MS 5U
#define IMU_HEADING_PERIOD_MS 5U

/* 2026 H: continuous stadium track and camera ball-on-beam control. */
#define H_TASK_CAR_LAP_STOP 2U
#define H_TASK_STATIC_BALL 3U
#define H_TASK_AB_CENTER_BALL 4U
#define H_TASK_LAP_CENTER_BALL 5U
#define H_TASK_LAP_ARBITRARY_BALL 6U
#define H_DEFAULT_TASK H_TASK_CAR_LAP_STOP

/* Continuous cruise speed with route-aware steering gain selection. */
#define H_TEMP_TRACK_TUNING_MODE 1U
#define H_TUNING_H2_CRUISE_SPEED_TICKS 13
#define H_TUNING_BALL_CRUISE_SPEED_TICKS 9
#define H_TUNING_CURVE_STEER_LEAD_MM 115
#define H_TUNING_CURVE_STEER_EXIT_MM 0
#define H_TUNING_CURVE_STEERING_FF_X4 0
#define H_TUNING_CURVE_FF_ENTRY_RAMP_MM 115
#define H_TUNING_CURVE_FF_EXIT_RAMP_MM 115
#define H_TUNING_DECEL_STEP_MS 50U
#define H_TUNING_H2_ACCEL_STEP_MS 80U
#define H_TUNING_BALL_ACCEL_STEP_MS 120U
#define H_TUNING_AUTO_FINISH_ENABLE 1U
#define H_TUNING_MARKER_MIN_TIME_MS 14000U
#define H_TUNING_MARKER_MIN_ACTIVE_SENSORS 3U
#define H_TUNING_MARKER_X1_HALF_MASK 0x0FU
#define H_TUNING_MARKER_X8_HALF_MASK 0xF0U
#define H_TUNING_MARKER_MIN_LAP_DISTANCE_MM 5600
#define H_TUNING_MARKER_MAX_LAP_DISTANCE_MM 6800
#define H_TUNING_MARKER_DEBOUNCE_MS 6U
#define H_TUNING_MARKER_MAX_TIME_MS 30000U
#define H_TUNING_TIMEOUT_MS 120000U

#define H_ROUTE_AB_MM 1500
#define H_ROUTE_HALF_CIRCLE_MM 1571
#define H_ROUTE_CD_END_MM 4571
#define H_ROUTE_LAP_MM 6142
#define H_CURVE_APPROACH_MM 400
#define H_CURVE_STEER_LEAD_MM 250
#define H_FINISH_DECEL_START_MM 5700
#define H_FINISH_PASS_MM 240
#define H_TASK4_PASS_B_MM 100

#define H_FAST_STRAIGHT_SPEED_TICKS 8
#define H_FAST_CURVE_SPEED_TICKS 5
#define H_STABLE_STRAIGHT_SPEED_TICKS 4
#define H_STABLE_CURVE_SPEED_TICKS 3
#define H_FINISH_APPROACH_SPEED_TICKS 2
#define H_FAST_RAMP_STEP_MS 180U
#define H_STABLE_RAMP_STEP_MS 450U

#define H_LINE_STRAIGHT_KP 2
#define H_LINE_STRAIGHT_KD 0
#define H_LINE_CURVE_KP 6
#define H_LINE_CURVE_KD 0
#define H_LINE_SCALE 8
#define H_LINE_STRAIGHT_CORRECTION_LIMIT_TICKS 2
#define H_LINE_CURVE_CORRECTION_LIMIT_TICKS 2
#define H_LINE_STRAIGHT_CORRECTION_SLEW_X4 1
#define H_LINE_CURVE_CORRECTION_SLEW_X4 1
#define H_LINE_DERIVATIVE_LIMIT 4
#define H_LINE_LARGE_ERROR 5
#define H_LINE_LOST_SPEED_TICKS 3
#define H_LINE_RECOVERY_CORRECTION_TICKS 2
#define H_LINE_MIN_VISIBLE_WHEEL_SPEED_TICKS 1
#define H_LINE_RECOVERY_START_MS 45U
#define H_LINE_SPEED_REDUCTION_START_MS 100U
#define H_CURVE_STEERING_FEEDFORWARD_TICKS 0
#define H_CURVE_STEERING_EXTRA_TICKS 0
#define H_LINE_LOST_TIMEOUT_MS 600U

/* 24H-proven line loop: weighted sensor error directly adjusts PWM. */
#define H_LINE_PWM_STATIC 22
#define H_LINE_PWM_PER_SPEED_TICK 2
#define H_LINE_PWM_ERROR_GAIN 3
#define H_LINE_PWM_CORRECTION_LIMIT 21
#define H_LINE_PWM_SLEW_PER_UPDATE 3

/* The main array recognizes the transverse A line until two extra sensors
 * receive their final pin allocation. */
#define H_MARKER_MIN_ACTIVE_SENSORS 6U
#define H_MARKER_CLEAR_MS 40U
#define H_MARKER_DEBOUNCE_MS 4U
#define H_MARKER_ARM_DISTANCE_MM 500
#define H_MARKER_MIN_LAP_DISTANCE_MM 5500

/* Position is represented in 0.1 mm, angle in 0.001 degree. */
#define H_BALL_CONTROL_PERIOD_MS 10U
#define H_BALL_VISION_TIMEOUT_MS 100U
#define H_BALL_MIN_CONFIDENCE 60U
#define H_BALL_KP_MDEG_PER_MM 205
#define H_BALL_KD_MDEG_PER_MMPS 75
#define H_BALL_KI_MDEG_PER_MM_S 0
#define H_BALL_ACCEL_FF_MDEG_PER_MMPS2 8
#define H_BALL_CONTROL_SIGN 1
#define H_BALL_ANGLE_LIMIT_MDEG 7000
#define H_BALL_INTEGRAL_LIMIT_TENTH_MM_MS 200000
#define H_BALL_POSITION_LIMIT_TENTH_MM 1100
#define H_BALL_TARGET_LIMIT_TENTH_MM 1000
#define H_BALL_WAYPOINT_TENTH_MM 500
#define H_BALL_WAYPOINT_TOL_TENTH_MM 50
#define H_BALL_FINAL_TOL_TENTH_MM 50
#define H_BALL_FINAL_SPEED_TENTH_MMPS 200
#define H_BALL_WAYPOINT_SETTLE_MS 120U
#define H_BALL_FINAL_SETTLE_MS 300U
#define H_BALL_FAULT_GRACE_MS 150U

#define H_ROD_NEUTRAL_MDEG 0
#define H_ROD_MIN_MDEG (-H_BALL_ANGLE_LIMIT_MDEG)
#define H_ROD_MAX_MDEG H_BALL_ANGLE_LIMIT_MDEG

#define H_ACTIVE_BRAKE_MS 120U
#define H_TASK2_TIMEOUT_MS 40000U
#define H_TASK3_TIMEOUT_MS 5000U
#define H_TASK4_TIMEOUT_MS 10000U
#define H_TASK56_TIMEOUT_MS 35000U

#define ENCODER_LEFT_SIGN (-1)
#define ENCODER_RIGHT_SIGN 1

#define LINE_BASE_LEFT_DUTY 40U
#define LINE_BASE_RIGHT_DUTY 40U
#define LINE_KP 6
#define LINE_KD 1
#define LINE_CENTER_MASK 0x18U
#define LINE_OUTER_MASK 0xC3U
#define LINE_LOST_LEFT_DUTY 44U
#define LINE_LOST_RIGHT_DUTY 36U

#define GYRO_HEADING_KP 2
#define GYRO_HEADING_CORR_DIV 900
#define GYRO_HEADING_CORR_MAX 6
#define GYRO_DEAD_RAW 8
#define GYRO_FAIL_LIMIT_MS 100U
#define GYRO_PWM_TICKS_PER_PERCENT (PWM_PERIOD_TICKS / 100U)

#define START_BOOST_LEFT_DUTY 60U
#define START_BOOST_RIGHT_DUTY 60U
#define START_BOOST_MS 180U
#define KEY_DEBOUNCE_MS 30U
#define KEY_RELEASE_ARM_MS 50U

/* Initial 3-loop values; tune after encoder PPR and chassis dimensions. */
#define SPEED_PID_KP 18
#define SPEED_PID_KI 3
#define SPEED_PID_KD 0
#define SPEED_PID_SCALE 10
#define SPEED_PID_OUTPUT_LIMIT 45
#define SPEED_PWM_HARD_LIMIT 105
#define SPEED_PID_INTEGRAL_LIMIT 1200
#define SPEED_FEEDFORWARD_PER_TICK 2
#define SPEED_STATIC_FRICTION_PWM 22
#define SPEED_PWM_SLEW_PER_UPDATE 3
#define WHEEL_SPEED_TARGET_LIMIT 20
#define SPEED_TUNE_TARGET_TICKS 2
#define ENCODER_WATCHDOG_MIN_PWM 20
#define ENCODER_NO_FEEDBACK_TIMEOUT_MS 800U
#define ENCODER_DIRECTION_FAULT_MS 100U
#define ENCODER_OVERSPEED_TICKS 30
#define ENCODER_OVERSPEED_FAULT_MS 50U

#define SQUARE_LINE_PID_KP 4
#define SQUARE_LINE_PID_KI 0
#define SQUARE_LINE_PID_KD 0
#define SQUARE_LINE_PID_SCALE 8
#define SQUARE_LINE_CORR_LIMIT 4
#define SQUARE_LINE_EDGE_ERROR 7
#define SQUARE_LINE_CENTER_RELEASE_CYCLES 1U
#define SQUARE_LINE_MEDIUM_ERROR 3
#define SQUARE_LINE_LARGE_ERROR 5
#define SQUARE_LINE_MEDIUM_SPEED_TICKS 6
#define SQUARE_LINE_LARGE_SPEED_TICKS 4

#define SQUARE_DISTANCE_PID_KP 8
#define SQUARE_DISTANCE_PID_KI 0
#define SQUARE_DISTANCE_PID_KD 12
#define SQUARE_DISTANCE_PID_SCALE 10

#define SQUARE_HEADING_PID_KP 6
#define SQUARE_HEADING_PID_KI 0
#define SQUARE_HEADING_PID_KD 12
#define SQUARE_HEADING_PID_SCALE 1000

#define SQUARE_CRUISE_SPEED_TICKS 8
#define SQUARE_APPROACH_MAX_SPEED_TICKS 2
#define SQUARE_SPEED_RAMP_STEP_MS 150U
#define SQUARE_TURN_MAX_SPEED_TICKS 3
#define SQUARE_TURN_MIN_SPEED_TICKS 1
#define SQUARE_CORNER_DEBOUNCE_MS 3U
#define SQUARE_CORNER_SIDE_X1_MASK 0x07U
#define SQUARE_CORNER_SIDE_X8_MASK 0xE0U
#define SQUARE_CORNER_MIN_TRAVEL_MM 800
#define SQUARE_CORNER_LOST_DEBOUNCE_MS 80U
#define SQUARE_CORNER_ARM_MS 500U
#define SQUARE_CORNER_CLEAR_MS 30U
#define SQUARE_LINE_LOST_TIMEOUT_MS 300U
#define SQUARE_DISTANCE_TOLERANCE_TICKS 8
#define SQUARE_STOP_SPEED_TOLERANCE 0
#define SQUARE_STOP_SETTLE_MS 150U
#define SQUARE_PRE_TURN_PAUSE_MS 400U
#define SQUARE_TURN_DIRECTION (-1)
#define SQUARE_TURN_ANGLE_MDEG 90000
#define SQUARE_HEADING_TOLERANCE_MDEG 1500
#define SQUARE_TURN_SETTLE_MS 80U
#define SQUARE_TURN_TIMEOUT_MS 5000U
#define SQUARE_TURN_LINE_CLEAR_MS 20U
#define SQUARE_TURN_LINE_MIN_ANGLE_MDEG 60000
#define SQUARE_TURN_LINE_DEBOUNCE_MS 6U
#define SQUARE_REACQUIRE_DEBOUNCE_MS 8U
#define SQUARE_REACQUIRE_SETTLE_MS 40U
#define SQUARE_REACQUIRE_SCAN_DELAY_MS 80U
#define SQUARE_REACQUIRE_SCAN_HALF_MS 550U
#define SQUARE_REACQUIRE_SCAN_ANGLE_MDEG 16000
#define SQUARE_REACQUIRE_FORWARD_SPEED_TICKS 2
#define SQUARE_REACQUIRE_MAX_SPEED_TICKS 2
#define SQUARE_REACQUIRE_MIN_SPEED_TICKS 1
#define SQUARE_REACQUIRE_TIMEOUT_MS 3000U
#define SQUARE_CONTINUOUS_RUN 1U
#define SQUARE_TOTAL_CORNERS 4U

/* Empirical chassis calibration profile. */
#define CAL_STRAIGHT_SPEED_TICKS 3
#define CAL_OFFSET_SPEED_TICKS 1
#define CAL_TURN_SPEED_TICKS 2
#define CAL_STRAIGHT_MIN_DISTANCE_MM 700
#define CAL_STRAIGHT_MAX_DISTANCE_MM 1300
#define CAL_STRAIGHT_TIMEOUT_MS 35000U
#define CAL_CORNER_MIN_ACTIVE 6U
#define CAL_CORNER_CLEAR_MS 30U
#define CAL_CORNER_DEBOUNCE_MS 8U
#define CAL_TURN_TARGET_MDEG 360000
#define CAL_TURN_WRONG_DIRECTION_MDEG 15000
#define CAL_TURN_MAX_WHEEL_DISTANCE_MM 1600
#define CAL_TURN_SETTLE_MS 150U
#define CAL_TURN_TIMEOUT_MS 15000U
#define CAL_OFFSET_MAX_DISTANCE_MM 300
#define CAL_OFFSET_TIMEOUT_MS 8000U

#endif
