#ifndef COMPETITION_BUILD_H
#define COMPETITION_BUILD_H

#define COMPETITION_BUILD_ALL 0U
#define COMPETITION_BUILD_H2_ONLY 2U
#define COMPETITION_BUILD_H3_ONLY 3U
#define COMPETITION_BUILD_H4_ONLY 4U
#define COMPETITION_BUILD_H5_ONLY 5U
#define COMPETITION_BUILD_H6_ONLY 6U

/* Keep H2 fixed until the dedicated task selector pins are assigned. */
#ifndef COMPETITION_BUILD_TARGET
#define COMPETITION_BUILD_TARGET COMPETITION_BUILD_H2_ONLY
#endif

#define COMPETITION_DEFAULT_TASK 2U

#if (COMPETITION_BUILD_TARGET > COMPETITION_BUILD_H6_ONLY)
#error "COMPETITION_BUILD_TARGET is invalid"
#endif

#if (COMPETITION_BUILD_TARGET != COMPETITION_BUILD_ALL) && \
    (COMPETITION_BUILD_TARGET != COMPETITION_BUILD_H2_ONLY)
#error "The selected competition task is not implemented yet"
#endif

#endif
