#ifndef TASK2_CONFIG_H
#define TASK2_CONFIG_H

/* Frozen from h2-final-mcu-precise-stop. */
#define TASK2_CONTROL_PERIOD_MS 5U
#define TASK2_CRUISE_SPEED_TICKS 13
#define TASK2_FINISH_SPEED_TICKS 2
#define TASK2_ACCEL_STEP_MS 80U
#define TASK2_DECEL_STEP_MS 50U

#define TASK2_LINE_LARGE_ERROR 5
#define TASK2_LINE_LOST_SPEED_TICKS 3
#define TASK2_LINE_SPEED_REDUCTION_MS 100U
#define TASK2_LINE_LOST_TIMEOUT_MS 600U
#define TASK2_PWM_STATIC 22
#define TASK2_PWM_PER_SPEED_TICK 2
#define TASK2_PWM_ERROR_GAIN 3
#define TASK2_PWM_CORRECTION_LIMIT 21

#define TASK2_MARKER_CLEAR_MS 40U
#define TASK2_MARKER_ARM_MS 1000U
#define TASK2_MARKER_MIN_TIME_MS 14000U
#define TASK2_MARKER_MIN_ACTIVE 3U
#define TASK2_MARKER_DEBOUNCE_MS 6U
#define TASK2_MARKER_MAX_TIME_MS 30000U
#define TASK2_LINE_CENTER_MASK 0x18U
#define TASK2_LINE_OUTER_MASK 0xC3U

#define TASK2_ROUTE_LAP_MM 6142
#define TASK2_FINISH_PASS_MM 240
#define TASK2_ACTIVE_BRAKE_MS 120U
#define TASK2_TIMEOUT_MS 120000U

#endif
